import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ConfigProvider } from "antd";
import TanstackProvider from "providers/TanstackProvider";
import "./globals.css";
import ThemeProvider from "@providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ConfigProvider>
        <body className={inter.className}>
          <TanstackProvider>
            <ThemeProvider>
              <div>{children}</div>
            </ThemeProvider>
          </TanstackProvider>
        </body>
      </ConfigProvider>
    </html>
  );
}
